name = "pocapoco"
main = ".open-next/worker.js"
compatibility_date = "2026-03-03"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "pocapoco-db"
database_id = "ac37dad1-4555-43c9-99da-692c70c4e1c1"

[vars]
# 本番では `wrangler secret put ADMIN_PASSWORD` で設定推奨
ADMIN_PASSWORD = "pocapoco_lin1013"
